In [19]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [34]:
dataset = pd.read_csv('../Data.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [35]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:,1:3])

In [22]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [23]:
print(X)

[[1.0 0.0 0.0 40.0 72000.0]
 [1.0 0.0 0.0 32.0 80000.0]
 [0.0 0.0 1.0 40.0 90000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 40.0 67666.66666666667]
 [1.0 0.0 0.0 37.2 58000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 40.0 67666.66666666667]]


In [24]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [25]:
print(y)

[0 0 1 0 0 1 1 0 1 1 1]


In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [27]:
print(X_train)

[[0.0 1.0 0.0 40.0 67666.66666666667]
 [1.0 0.0 0.0 37.2 58000.0]
 [1.0 0.0 0.0 32.0 80000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 40.0 72000.0]
 [0.0 1.0 0.0 40.0 67666.66666666667]]


In [28]:
print(X_test)

[[0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 40.0 90000.0]]


In [29]:
print(y_train)

[1 1 0 0 1 0 0 1]


In [30]:
print(y_test)

[0 1 1]


In [31]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:,3:] = sc.transform(X_test[:,3:])

In [32]:
print(X_train)

[[0.0 1.0 0.0 0.9048009891843765 0.22795136315904266]
 [1.0 0.0 0.0 0.11923733965995774 -1.0312085476242412]
 [1.0 0.0 0.0 -1.3396665808853936 1.834465732089438]
 [0.0 1.0 0.0 -1.9007834734028362 -1.5522402348449102]
 [1.0 0.0 0.0 0.06312565040821268 0.14111274862226386]
 [0.0 0.0 1.0 0.34368409666693395 -0.6404347822087395]
 [1.0 0.0 0.0 0.9048009891843765 0.7924023576481001]
 [0.0 1.0 0.0 0.9048009891843765 0.22795136315904266]]


In [33]:
print(X_test)

[[0.0 0.0 1.0 -2.742458812179 -2.333787765675914]
 [1.0 0.0 0.0 3.1492685592541467 1.7042078102842708]
 [0.0 0.0 1.0 0.9048009891843765 3.13704495014111]]
